### ISSUE TITLE
Deploying on AWS Lambda

### ISSUE THREAD

**Issue by svaidyans** [jalan/pdftotext#37]
Hi Jalan,

Thanks for a wonderful library.  I am trying to deploy a small python 3.7 which uses pdftotext on AWS-Lambda.  I was able to run this successfully on my local machine (Mac).  I then followed the AWS documentation on creating the package with a virtual environment.  However I am still getting module not found error.  By any chance is there a complete build package which has all the dependent packages (poppler, et al.) that I can use in AWS Lambda.  If you so, can you share the location please.  Many thanks in advance.

Regards,
Vaidya.

**Comment by rameezcubet** [comment]
@svaidyans found any solution? were you able to work it out?

**Comment by eliezer** [comment]
Hi Guys,
I'm using https://www.serverless.com/ framework with plugin serverless-python-requirements in my project. I finally found a solution to build native dependencies in AWS Lambda.

Using Docker to create a package with native dependencies:

Dockerfile:
```
FROM lambci/lambda:build-python3.6
RUN pip install --upgrade pip
RUN yum -y remove cmake
RUN pip install cmake --upgrade
RUN yum -y install poppler-cpp-devel
```


serverless.yml

```
frameworkVersion: ">=1.3.4 <2.11.2"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6

custom:
  pythonRequirements:
    useDownloadCache: false
    useStaticCache: false
    invalidateCaches: true
    dockerizePip: true
    dockerFile: Dockerfile
    dockerExtraFiles:
      - /usr/lib64/libpoppler-cpp.so.10      
      - /usr/lib64/libpoppler.so.46          
      - /usr/lib64/libopenjpeg.so.2
```

The magic has happened in 'dockerExtraFiles' responsible to copy the native libraries to your lambda package.
